# Generated by Django 2.2.7 on 2020-02-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expenseinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseinfo',
            old_name='expenses',
            new_name='expenditure',
        ),
    ]
