# Generated by Django 3.0 on 2020-03-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_tite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('artist_id', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artist_of_song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_of_song', to='core.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ManyToManyField(to='core.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_of_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_of_album', to='core.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Song'),
        ),
    ]
