# Generated by Django 3.0 on 2020-03-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_of_song',
        ),
    ]
