# Generated by Django 3.0 on 2020-03-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_song_artist_of_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_of_album',
        ),
    ]
