# Generated by Django 3.0 on 2020-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200330_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_of_album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_of_song',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_of_song',
            field=models.ManyToManyField(to='core.Artist'),
        ),
    ]
