# Generated by Django 2.2.4 on 2019-09-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
    ]
